application: connexus
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /assets
  static_dir: assets

- url: /tasks/trending_stream
  script: Source.Services.summarize_trending_stream.app
  login: admin

- url: /tasks/delete
  script: main.app
  login: admin

- url: .*
  script: main.app
  login: required


libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "2.6"
