application: connexus-1078
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: /tasks/trending_stream
  script: Source.Services.summarize_trending_stream.app
  login: admin

- url: /tasks/delete
  script: Source.Services.storage.app
  login: admin

- url: /_ah/spi/.*
  script: Source.BackEnd.backend.APPLICATION

- url: /backend/uploader.*
  script: Source.BackEnd.BackendFileuploadHandler.app

- url: .*
  script: main.app
  login: required


libraries:
- name: webapp2
  version: 2.5.2

- name: jinja2
  version: 2.6

- name: pycrypto
  version: latest

- name: endpoints
  version: 1.0
